[tool.poetry]
name = "pybraendstofpriser"
version = "2.2.0"
description = "Library for fetching fuel prices from Fuelprices.dk API"
authors = ["Malene Trab <malene@trab.dk>"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
aiohttp = "^3.13.2"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
